let track='quality',skill='api',pending='PENDING';
const skills={api:{title:'API regression testing',count:'F-12 · confirmed',fact:'F-12',linked:['APP-01','APP-02'],story:'An API regression story worth reusing.',usage:'Resume v3 / Northstar',gap:'Playwright depth remains unknown. Ask about expectations; don’t invent expertise.'},database:{title:'Database test design',count:'F-18 · confirmed',fact:'F-18',linked:['APP-01','APP-07'],story:'Transaction boundaries, with a source.',usage:'Resume v3 / Northstar',gap:'No confirmed performance benchmark result. A test fixture is not proof of production throughput.'},experience:{title:'Commercial QA experience',count:'F-23 · confirmed',fact:'F-23',linked:['APP-01','APP-04'],story:'Four years, with explicit scope.',usage:'Analysis / experience dimension',gap:'Years of QA do not establish team leadership.'},lead:{title:'QA platform leadership',count:'F-31 · pending',fact:'F-31',linked:[],story:'Leadership is a hypothesis to review.',usage:'No permitted generated usage',gap:'Market interest cannot confirm leadership. Review the source and your actual role first.'}};
function render(){const keys=track==='quality'?['api','database','experience']:['lead','experience'];if(!keys.includes(skill))skill=keys[0];$('#capabilities').innerHTML=keys.map(k=>`<button class="capability" aria-pressed="${skill===k}" data-skill="${k}"><span>${skills[k].title}<small>${skills[k].count}</small></span><span class="${k==='lead'?'amber':'cyan'}">${skills[k].linked.length} linked</span></button>`).join('');$$('[data-skill]').forEach(b=>b.addEventListener('click',()=>{skill=b.dataset.skill;render();announce(`${skills[skill].title}: ${skills[skill].linked.length} connected opportunities.`);}));const s=skills[skill],f=FIXTURES.facts.find(f=>f.id===s.fact);
$('#connection-count').textContent=`${s.linked.length} linked`;$('#market-explanation').textContent=s.linked.length?'These saved roles ask for related evidence. Fit still depends on all seven dimensions.':'No reviewed vacancy matching is attached to this leadership fixture.';$('#market-roles').innerHTML=s.linked.length?s.linked.map(id=>{const a=FIXTURES.applications.find(a=>a.id===id);return `<article class="market-role"><h3>${a.role}</h3><p>${a.company} · ${a.salary}</p><div class="spread"><span class="badge ${a.recommendation==='APPLY'?'good':'warn'}">${a.recommendation}</span><button class="linkbutton" data-role="${a.id}">Inspect fit</button></div></article>`;}).join(''):'<div class="note danger" style="margin-top:24px"><p>BLOCK · pending evidence cannot support market fit or generated content.</p></div>';
$$('[data-role]').forEach(b=>b.addEventListener('click',()=>{const a=FIXTURES.applications.find(a=>a.id===b.dataset.role);openDialog(a.company+' · evidence-based fit',`<span class="badge">${a.recommendation}</span><p>${a.reason}</p><p class="source">Selected supporting fact: ${s.fact}. This is partial fit context, not an ATS score.</p><p>${a.next}</p>`);}));$('#story-title').textContent=skill==='lead'&&f.status==='CONFIRMED'?'Leadership reviewed; content usage still pending.':skill==='lead'&&f.status==='REJECTED'?'Leadership proposal rejected.':s.story;$('#story-copy').textContent=f.statement;$('#story-fact').textContent=`${f.id} · ${f.status}`;$('#story-claim').textContent=f.status==='CONFIRMED'?(skill==='lead'?'Claim not created':skill==='experience'?'Matching evidence · confirmed':'CL-08 · PASS'):'Claim blocked';$('#story-usage').textContent=s.usage;$('#story-source').textContent=f.source;$('#gap-note').textContent=skill==='lead'&&f.status==='CONFIRMED'?'Exact wording confirmed in the demo. A new Claim and reviewed usage are still required.':s.gap;if(skill==='lead'&&f.status==='CONFIRMED')$('#market-roles').innerHTML='<div class="note info" style="margin-top:24px"><p>No matching result yet. A confirmed fact alone does not establish fit for a role.</p></div>';$('#story-reuse').disabled=f.status!=='CONFIRMED'||skill==='lead';$('#track-note').textContent=track==='lead'?'Leadership track is exploratory. No confirmed leadership fact exists.':'Skill labels are an index into confirmed facts. They are not new career claims.';
}
$$('[data-track]').forEach(b=>b.addEventListener('click',()=>{track=b.dataset.track;$$('[data-track]').forEach(x=>x.setAttribute('aria-pressed',x===b));render();announce(`Career track: ${b.textContent}.`);}));
$('#story-evidence').addEventListener('click',()=>{const f=FIXTURES.facts.find(f=>f.id===skills[skill].fact);openDialog('Evidence story · '+f.id,`<span class="badge ${f.status==='CONFIRMED'?'good':'warn'}">${f.status}</span><p>${f.statement}</p><div class="source">${f.source}</div><p>${f.status==='CONFIRMED'?'The exact fact can inform related matching. Generated usage still needs Claim provenance and content approval.':'No generated usage is permitted while this fact is pending.'}</p>`);});
$('#story-reuse').addEventListener('click',()=>{if(skill==='experience'){openDialog('Suggested reuse · experience','<span class="badge ai">AI recommendation</span><p>Before: QA experience.</p><p>After: Four years of commercial QA experience.</p><p>Reason: make duration explicit. Evidence: confirmed F-23. Risk: duration does not establish seniority or leadership.</p><p>Review the exact wording before generating or approving content.</p>');return;}openDialog('Suggested reuse · human review','<span class="badge ai">AI recommendation</span><p>Before: Tested backend services.</p><p>After: Built API regression tests with Python and pytest; tested PostgreSQL transaction boundaries.</p><p>Reason: expose relevant evidence. Facts F-12 and F-18. Risk: no leadership or performance claim is supported.</p><p><a href="../concept-b/index.html">Open accept / edit / reject review in Concept B</a></p>');});
$('#pending-source').addEventListener('click',()=>openDialog('Unreviewed demo excerpt','<span class="badge warn">Original extraction · untrusted source</span><p class="source">“Led the migration of the QA platform.”</p><p>Importer proposed F-31. A sentence in a source does not independently establish the candidate’s role or leadership scope.</p>'));
$('#leave-pending').addEventListener('click',()=>announce('F-31 remains pending. It cannot support content.'));
$('#review-fact').addEventListener('click',()=>{
openDialog('Review pending fact · F-31','<span class="demo">Local synthetic review only.</span><p class="source">Led the migration of the QA platform.</p><p>Confirm only if the exact role and scope are true for the demo candidate. Reject if unsupported.</p><div class="actions"><button id="confirm-demo-fact" class="primary">Confirm demo fact</button><button id="reject-demo-fact">Reject demo fact</button></div>');
function finish(state){pending=state;const f=FIXTURES.facts.find(f=>f.id==='F-31');f.status=state;skills.lead.count=`F-31 · ${state.toLowerCase()}`;$('#pending-state').textContent=state;$('#pending-state').className='badge '+(state==='CONFIRMED'?'good':'block');$('#pending-count').textContent='Review decision recorded';$('#review-fact').disabled=true;$('#leave-pending').disabled=true;$('#context-dialog').close();render();$('#story-title').setAttribute('tabindex','-1');$('#story-title').focus();announce(`F-31 ${state.toLowerCase()} by explicit demo action. No existing content was changed.`);}
$('#confirm-demo-fact').addEventListener('click',()=>finish('CONFIRMED'));$('#reject-demo-fact').addEventListener('click',()=>finish('REJECTED'));
});render();
