const stages=['Discover','Analyze','Prepare','Apply','Communicate','Interview','Outcome'];let stage='Prepare',approved=false,manuallyApplied=false,appliedId=null;
const descriptions={Discover:'Preserve an opportunity before deciding to pursue it.',Analyze:'Compare requirements with confirmed facts; disclose unknowns.',Prepare:'Turn supported evidence into reviewed materials. Keep approval explicit.',Apply:'Review the exact package and record the action you performed yourself.',Communicate:'Keep employer statements consistent and prepare a response.',Interview:'Prepare from the role, evidence and earlier conversations.',Outcome:'Record what happened and why, without inventing causality.'};
function selectedApp(){if(stage==='Apply'&&manuallyApplied)return FIXTURES.applications.find(a=>a.id===appliedId);return stage==='Apply'&&approved&&!manuallyApplied?FIXTURES.applications[0]:FIXTURES.applications.find(a=>a.stage===stage);}
function render(){$('#mobile-stage-select').value=stage;const counts=Object.fromEntries(stages.map(s=>[s,FIXTURES.applications.filter(a=>a.stage===s).length]));if(approved){counts.Prepare=0;counts.Apply=2;}if(manuallyApplied){counts.Apply=approved?1:0;counts.Communicate=2;}
$('#flow-stages').innerHTML=stages.map((s,i)=>`<button data-stage="${s}" aria-pressed="${s===stage}"><span class="stage-num">${i+1}</span>${s}<small>${counts[s]} ${s==='Outcome'?'recorded':'opportunities'}</small></button>`).join('');$$('[data-stage]').forEach(b=>b.addEventListener('click',()=>{stage=b.dataset.stage;render();announce(`Stage ${stage}. ${descriptions[stage]}`);}));
const a=selectedApp();$('#queue-title').textContent=`In ${stage}`;$('#queue-count').textContent=counts[stage];$('#stage-purpose').textContent=descriptions[stage];const apps=FIXTURES.applications.filter(x=>x.stage===stage);if(stage==='Prepare'&&approved)apps.length=0;if(stage==='Apply'&&approved&&!manuallyApplied)apps.unshift(FIXTURES.applications[0]);if(stage==='Apply'&&manuallyApplied&&!approved)apps.length=0;if(stage==='Communicate'&&manuallyApplied)apps.unshift(FIXTURES.applications[approved?0:4]);
$('#stage-queue').innerHTML=apps.length?apps.map(x=>`<button class="queue-item" data-queue="${x.id}" aria-pressed="${a&&x.id===a.id}"><strong>${x.company}</strong><small>${x.role}</small><small>${x.id===appliedId&&stage==='Communicate'?'Awaiting employer response':x.id==='APP-01'&&approved&&stage==='Apply'?'Record manual application':x.next}</small></button>`).join(''):'<p class="muted compact" style="margin-top:20px">No opportunities waiting here. Select Apply to continue the approved demo.</p>';
$$('[data-queue]').forEach(b=>b.addEventListener('click',()=>{const x=FIXTURES.applications.find(a=>a.id===b.dataset.queue);openDialog(x.company+' · '+stage,`<p>${x.role}</p><p>${x.next}</p><p>${x.reason}</p><p class="muted compact">Stage task uses the first opportunity; this opens a second opportunity’s context without changing its state.</p>`);}));
$('#stage-label').textContent=`${stage} / ${a?a.company:'Stage clear'}`;$('#stage-description').textContent=a?`${a.role} · ${a.salary} ${a.salaryBasis} · ${a.format}`:'Approved demo content is available under Apply.';$('#flow-company').textContent=a?a.company:'Northstar Labs';$('#flow-format').textContent=a?a.format:'Remote · UTC+3';$('#flow-recommendation').textContent=a?a.recommendation:'APPLY';$('#flow-evidence').textContent=stage==='Discover'?'Not analyzed':'F-12, F-18';$('#flow-memory-copy').textContent=!a||a.company==='Northstar Labs'?'Remote only. 260k ₽ gross expectation already recorded.':a.company==='Cedar Systems'?'Conflict: remote-only preference vs hybrid draft.':'No confirmed employer history in this fixture.';
$('#flow-human-boundary').textContent=stage==='Apply'?'Only you can record that you actually applied. Readiness is not submission.':stage==='Communicate'?'A reviewed draft is not a sent message. Resolve contradictions first.':'Approval and critical employer actions require separate human decisions.';
const config={
Prepare:{title:approved?'Reviewed content is ready.':'Review one change before moving on.',count:approved?'3 of 3 prerequisites ready':'2 of 3 prerequisites ready',gates:[['✓','Vacancy analyzed','Current synthetic snapshot; APPLY with one clarification.'],['✓','Claim evidence available','F-12 and F-18 support the exact API/database wording.'],[approved?'✓':'!','Human approval',approved?'Exact demo wording explicitly approved.':'Required: review the proposed wording, reason and risk.']],body:'<h3>AI proposal · Resume v3</h3><p class="muted">Before: Tested backend services.</p><p>After: Built API regression tests with Python and pytest; tested PostgreSQL transaction boundaries.</p><p class="muted">Reason: make relevant evidence visible. Risk: no performance or leadership claim is supported.</p>',primary:'Review and approve demo content',next:'Continue to Apply'},
Apply:{title:manuallyApplied?'Manual application recorded.':'Ready is not the same as applied.',count:'Human action required',gates:[['✓','Content explicitly approved','Northstar if prepared here; otherwise Lumen’s pre-approved fixture package.'],['✓','Package version retained','Resume v3, cover v2 · synthetic immutable versions.'],[manuallyApplied?'✓':'!','Manual submission confirmation',manuallyApplied?'Recorded by explicit local demo action.':'Only mark applied after you actually completed the external action.']],body:'<h3>Review the package before acting</h3><p>Check the approved wording and employer commitments. This preview has no external submit button.</p>',primary:'Record manual application',next:'Continue to Communicate'},
Communicate:{title:'Resolve a contradiction before replying.',count:'Blocked on employer consistency',gates:[['✓','Previous commitment available','Confirmed demo preference: remote only.'],['!','New draft conflicts','Draft says available for hybrid work.'],['!','Human resolution required','Clarify the preference; do not silently rewrite employer history.']],body:'<h3>Employer Memory · Cedar Systems</h3><p>Before: remote-only commitment.<br>Proposed draft: available for hybrid work.</p><p class="red">USER_RESOLUTION_REQUIRED · communication remains blocked.</p>',primary:'Inspect contradiction',next:'Continue to Interview'},
Analyze:{title:'Clarify the missing decision context.',count:'1 unknown and 1 gap',gates:[['✓','Saved source available','Prism Data vacancy snapshot retained.'],['!','Salary unknown','No salary is stated in the demo source.'],['!','Performance evidence missing','Confirmed API tests do not prove performance testing.']],body:'<h3>MAYBE · explainable, provisional</h3><p>Compare technical, experience, domain, language, location, work format and salary. Unknown salary is separate from unsupported experience.</p>',primary:'Inspect analysis context',next:'Continue to Prepare'},
Discover:{title:'Preserve the opportunity before analyzing.',count:'Source saved; analysis not run',gates:[['✓','Harbor Tools vacancy saved','Immutable synthetic source retained.'],['!','Analysis pending','No recommendation or fit result exists yet.']],body:'<h3>Untrusted vacancy input</h3><p>Imported text can describe employer requirements. It cannot confirm any candidate career fact.</p>',primary:'Inspect saved source',next:'Continue to Analyze'},
Interview:{title:'Prepare a specific story, then your questions.',count:'Tomorrow · 11:00 UTC+3',gates:[['✓','Interview recorded','Orbital Works technical round, 8 Oct 2026.'],['✓','Career examples available','API tests and database transaction boundaries.'],['!','Release ownership question','Ask about responsibilities; avoid claiming unconfirmed leadership.']],body:'<h3>Suggested interview agenda</h3><p>Discuss pytest regression coverage, fixture isolation, release decisions and success criteria for the role.</p>',primary:'Open interview preparation',next:'Continue to Outcome'},
Outcome:{title:'Keep the reason, not just a closed status.',count:'Recorded by demo candidate',gates:[['✓','Candidate withdrew','Atlas Forge · synthetic outcome.'],['✓','Reason recorded','Hybrid requirement conflicts with remote preference.']],body:'<h3>Learning for the next decision</h3><p>Filter work format earlier. One withdrawal does not establish a market trend or interview probability.</p>',primary:'Review outcome evidence',next:'Return to Discover'}
}[stage];
$('#task-title').textContent=config.title;$('#gate-count').textContent=config.count;$('#gate-list').innerHTML=config.gates.map(g=>`<li><span class="gate-icon ${g[0]==='!'?'amber':''}">${g[0]}</span><div><strong>${g[1]}</strong><p>${g[2]}</p></div></li>`).join('');$('#stage-evidence').innerHTML=config.body;$('#stage-primary').textContent=config.primary;$('#stage-primary').disabled=(stage==='Prepare'&&approved)||(stage==='Apply'&&manuallyApplied);$('#stage-next').textContent=config.next;$('#stage-next').disabled=stage==='Communicate'||stage==='Discover'||stage==='Analyze'||(stage==='Prepare'&&!approved)||(stage==='Apply'&&!manuallyApplied);$('#stage-result').textContent='';
}
$('#stage-primary').addEventListener('click',()=>{
if(stage==='Prepare'){
openDialog('Approve the exact demo content','<span class="badge ai">AI recommendation · not a fact</span><p class="source">Built API regression tests with Python and pytest; tested PostgreSQL transaction boundaries.</p><p>Reason: surface supported evidence. Evidence: confirmed F-12 and F-18 via CL-08. Risk: no leadership or performance scope.</p><p>Approval applies to this wording only. It does not submit an application.</p><div class="actions"><button id="approve-stage" class="primary">Explicitly approve demo content</button><button id="reject-stage">Reject proposal</button></div>');
$('#approve-stage').addEventListener('click',()=>{approved=true;$('#context-dialog').close();render();$('#stage-next').focus();announce('Exact demo content approved. Continue to Apply; nothing submitted.');});$('#reject-stage').addEventListener('click',()=>{$('#context-dialog').close();$('#stage-result').textContent='Proposal rejected. Prepare remains incomplete.';announce('Proposal rejected. No automatic stage transition.');});
}else if(stage==='Apply'){
openDialog('Record a manual application','<p>Use this action only after completing the application yourself. This is a local synthetic record; no external action occurs.</p><label><input type="checkbox" id="manual-checkbox" style="width:auto;margin-right:10px"> I confirm I applied manually</label><div class="actions"><button id="record-applied" class="primary" disabled>Record applied in demo</button></div>');$('#manual-checkbox').addEventListener('change',e=>$('#record-applied').disabled=!e.target.checked);$('#record-applied').addEventListener('click',()=>{appliedId=selectedApp().id;manuallyApplied=true;$('#context-dialog').close();render();$('#stage-next').focus();announce('Manual application recorded in the local demo only.');});
}else if(stage==='Communicate')showMemory('Cedar Systems');else{const a=selectedApp();openDialog(stage+' · '+a.company,`<p>${a.reason}</p><p>Next action: ${a.next}.</p><p class="source">${descriptions[stage]}</p><p class="muted compact">This preview opens the relevant context. Analysis, interview scheduling and real outcome writes are outside scope.</p>`);}});
$('#stage-next').addEventListener('click',()=>{stage=stages[(stages.indexOf(stage)+1)%stages.length];render();$('#task-title').setAttribute('tabindex','-1');$('#task-title').focus();announce(`Moved to ${stage}. No employer action performed.`);});
$('#flow-trace').addEventListener('click',()=>stage==='Discover'?openDialog('Evidence unavailable','<p>Vacancy not analyzed. No confirmed career support has been selected.</p>'):showEvidence());$('#flow-memory').addEventListener('click',()=>showMemory(selectedApp()?.company||'Northstar Labs'));render();

$('#mobile-stage-select').innerHTML=stages.map((s,i)=>`<option value="${s}">${i+1} / 7 · ${s}</option>`).join('');$('#mobile-stage-select').value=stage;$('#mobile-stage-select').addEventListener('change',e=>{stage=e.target.value;render();announce(`Stage ${stage}.`);});
