let selected='APP-01',section='resume',review='DRAFT',content=FIXTURES.recommendation.after,editing=false;
function app(){return FIXTURES.applications.find(a=>a.id===selected);}
function list(){const q=$('#app-search').value.toLowerCase();const rows=FIXTURES.applications.filter(a=>a.stage!=='Outcome'&&`${a.company} ${a.role}`.toLowerCase().includes(q));$('#app-list').innerHTML=rows.map(a=>`<button class="app-item" aria-pressed="${selected===a.id}" data-app="${a.id}"><span class="company-icon">${a.initials}</span><span><strong>${a.company}</strong><small>${a.role}</small><span class="badge">${a.stage}</span></span></button>`).join('');$('#list-empty').hidden=rows.length>0;$$('[data-app]').forEach(b=>b.addEventListener('click',()=>selectApplication(b.dataset.app)));}
window.selectApplication=id=>{selected=id;$('#mobile-app-select').value=id;const a=app();$('#main-title').textContent=a.role;$('#workspace-company').textContent=a.company;$('#breadcrumb-company').textContent=a.company;$('#workspace-stage').textContent=a.stage+(a.stage==='Prepare'?' · not applied':'');$('#workspace-icon').textContent=a.initials;$('#workspace-salary').textContent=`${a.salary} · ${a.salaryBasis}`;$('#workspace-format').textContent=a.format;$('#workspace-recommendation').textContent=a.recommendation;$('#workspace-reason').textContent=a.reason;$('#memory-summary').textContent=a.company==='Northstar Labs'?'Already shared: remote only; 260k ₽ gross / month.':a.company==='Cedar Systems'?'Conflict: remote-only preference vs a new hybrid-work draft.':'No confirmed employer history in the fixture.';
const context=$('.workspace-context');context.querySelector('.tight').hidden=id!=='APP-01';context.querySelector('details').hidden=id!=='APP-01';context.querySelector('h3.amber').hidden=id!=='APP-01';context.querySelector('h3.amber').nextElementSibling.hidden=id!=='APP-01';
list();panel();announce(`${a.company} selected. Context preserved.`);};
function panel(){const a=app();const root=$('#workspace-panel');
if(section==='resume'&&selected==='APP-01'){
root.innerHTML=`<section class="review-work tight"><div class="spread"><span class="badge ai">AI recommendation · R-07</span><span class="badge ${review==='APPROVED'?'good':review==='REJECTED'?'block':'warn'}" id="review-badge">${review}</span></div><h2>Make API testing experience visible.</h2><p class="muted compact">Resume v3 / Experience / Northstar Labs</p><div class="diff"><div><span class="label">Before</span><p>${FIXTURES.recommendation.before}</p></div><div class="after"><span class="label">After · proposed</span><p id="proposal-text"></p></div></div><div class="why tight"><strong>Reason</strong><p class="compact">${FIXTURES.recommendation.reason}</p><strong>Risk</strong><p class="compact muted">${FIXTURES.recommendation.risk}</p><button class="linkbutton" id="review-evidence">Evidence: 2 confirmed facts → 1 claim</button></div><div id="edit-area" ${editing?'':'hidden'}><label>Edit proposed content<textarea id="review-edit" rows="3"></textarea></label><p class="muted small">This demo validates only two exact fixture wordings; other edits are blocked. No AI request.</p><div class="actions"><button id="save-edit">Save &amp; check fixture evidence</button><button id="cancel-edit">Cancel edit</button></div></div><div class="actions" id="review-actions"><button class="primary" id="accept-change" ${review!=='DRAFT'||editing?'disabled':''}>Accept suggestion</button><button id="edit-change" ${review!=='DRAFT'?'disabled':''}>Edit</button><button id="reject-change" ${review==='APPROVED'||review==='REJECTED'||editing?'disabled':''}>Reject</button></div><div class="review-footer tight"><div class="spread"><strong>Human approval</strong><button id="approve-content" ${review!=='ACCEPTED'?'disabled':''}>Approve content</button></div><p id="approval-help">${review==='APPROVED'?'Approved demo draft · not sent to employer.':'Accept the exact content before explicitly approving it. Nothing is submitted.'}</p></div><div class="status-live" id="review-result" role="status" style="margin-top:12px"></div></section>`;
$('#proposal-text').textContent=content;$('#review-edit').value=content;
$('#review-evidence').addEventListener('click',()=>showEvidence());
$('#accept-change').addEventListener('click',()=>{review='ACCEPTED';panel();$('#approve-content').focus();announce('Suggestion accepted. Explicit approval is still required.');});
$('#reject-change').addEventListener('click',()=>{review='REJECTED';editing=false;panel();$('#workspace-panel').setAttribute('tabindex','-1');$('#workspace-panel').focus();announce('Suggestion rejected. Original content retained in the demo.');});
$('#edit-change').addEventListener('click',()=>{editing=true;panel();$('#review-edit').focus();});
$('#cancel-edit').addEventListener('click',()=>{editing=false;panel();$('#edit-change').focus();});
$('#save-edit').addEventListener('click',()=>{const text=$('#review-edit').value;const allowed=[FIXTURES.recommendation.after,'Built API regression tests with Python and pytest.'];if(!allowed.includes(text)){$('#review-result').textContent='BLOCK: edited text has no validated fixture provenance. Restore a supported wording.';$('#review-result').setAttribute('role','alert');announce('Edit blocked. Unvalidated text cannot be accepted or approved.');return;}content=text;editing=false;review='DRAFT';panel();$('#accept-change').focus();announce('Supported fixture wording saved. Review it before acceptance.');});
$('#approve-content').addEventListener('click',()=>{review='APPROVED';panel();$('#workspace-panel').setAttribute('tabindex','-1');$('#workspace-panel').focus();announce('Content explicitly approved in this local demo. No application sent.');});
}else if(section==='match'&&selected==='APP-01'){
root.innerHTML=`<section class="stack"><h2>Requirements beside evidence</h2><p class="muted compact">${a.reason}</p><div class="requirement-row"><div class="spread"><h3>API regression with Python / pytest</h3><span class="badge good">Supported</span></div><p class="muted">Confirmed demo F-12 · exact scope retained</p></div><div class="requirement-row"><div class="spread"><h3>PostgreSQL transaction testing</h3><span class="badge good">Supported</span></div><p class="muted">Confirmed demo F-18</p></div><div class="requirement-row"><div class="spread"><h3>Playwright in production</h3><span class="badge warn">Unknown</span></div><p class="muted">No confirmed depth; do not invent experience.</p></div><button id="match-evidence">Inspect supported evidence</button><details><summary>Saved vacancy wording · untrusted</summary><p>Demo source snapshot: commercial QA, Python API tests, PostgreSQL and browser automation. Imported text cannot confirm career facts.</p></details></section>`;$('#match-evidence').addEventListener('click',()=>showEvidence());
}else if(section==='history'){
root.innerHTML=`<section class="stack"><h2>Context over time</h2><ul class="timeline"><li><time>7 Oct 2026</time><p>${a.next}. ${a.stage==='Prepare'?'Human approval is pending.':'Demo workflow event.'}</p></li><li><time>3 Oct 2026</time><p>${a.company==='Northstar Labs'?'Remote preference and salary expectation confirmed.':'Opportunity saved in synthetic tracker.'}</p></li><li><time>2 Oct 2026</time><p>Vacancy source snapshot preserved.</p></li></ul><button id="history-memory">Open confirmed employer context</button></section>`;$('#history-memory').addEventListener('click',()=>showMemory(a.company));
}else if(section==='cover'){
root.innerHTML='<section class="stack"><h2>Cover draft is not ready.</h2><span class="badge warn">Waiting for reviewed content</span><p class="muted">Review the resume suggestion and employer commitments before preparing the next document.</p><button id="return-resume">Return to resume review</button><button disabled>Generate cover · unavailable in this preview</button></section>';$('#return-resume').addEventListener('click',()=>{$('[data-section="resume"]').click();});
}else{
root.innerHTML=`<section class="stack"><h2>${a.next}</h2><p class="muted">${a.reason}</p><span class="badge">${a.stage}</span><p>No resume change is attached to this fixture. The complete review interaction belongs to Northstar Labs.</p><button id="back-northstar">Open Northstar review</button></section>`;$('#back-northstar').addEventListener('click',()=>selectApplication('APP-01'));
}}
$$('[data-section]').forEach(b=>b.addEventListener('click',()=>{section=b.dataset.section;$$('[data-section]').forEach(x=>x.setAttribute('aria-pressed',x===b));panel();announce(`Section: ${b.textContent}.`);}));
$('#app-search').addEventListener('input',list);$('#workspace-memory').addEventListener('click',()=>showMemory(app().company));list();panel();

$('#mobile-app-select').innerHTML=FIXTURES.applications.filter(a=>a.stage!=='Outcome').map(a=>`<option value="${a.id}">${a.company} · ${a.stage}</option>`).join('');$('#mobile-app-select').addEventListener('change',e=>selectApplication(e.target.value));
