let selected='APP-01', filter='decision';
function renderRows(){const rows=FIXTURES.applications.filter(a=>a.stage!=='Outcome').filter(a=>filter==='all'||(filter==='interview'?a.stage==='Interview':['APP-01','APP-03','APP-04'].includes(a.id)));
$('#pipeline-rows').innerHTML=rows.map(a=>`<tr class="${a.id===selected?'is-selected':''}"><td><button class="role-button" data-app="${a.id}" aria-pressed="${a.id===selected}"><strong>${a.company}</strong><small>${a.role}</small></button></td><td data-label="Stage"><span class="badge ${a.stage==='Interview'?'good':a.stage==='Communicate'?'warn':''}">${a.stage}</span></td><td data-label="Next action">${a.next}</td><td data-label="When" class="muted small">${a.due}</td></tr>`).join('');$('#result-count').textContent=`${rows.length} opportunities`;
$$('[data-app]').forEach(b=>b.addEventListener('click',()=>selectApplication(b.dataset.app)));}
window.selectApplication=id=>{const a=FIXTURES.applications.find(a=>a.id===id);selected=id;$('#inspector-title').textContent=a.company;$('#inspector-icon').textContent=a.initials;$('#inspector-role').textContent=a.role;$('#inspector-recommendation').textContent=a.recommendation;$('#inspector-stage').textContent=a.stage;$('#inspector-salary').textContent=`${a.salary} · ${a.salaryBasis}`;$('#inspector-reason').textContent=a.reason;$('#inspector-action').textContent=a.next;renderRows();announce(`Selected ${a.company}. ${a.next}.`);
const dimensions=$$('.inspector .dimension');dimensions[0].lastElementChild.textContent=a.id==='APP-06'?'Not analyzed':a.id==='APP-04'?'Performance evidence missing':'API evidence available';dimensions[1].lastElementChild.textContent=a.id==='APP-06'?'Not analyzed':'B2 confirmed';dimensions[2].lastElementChild.textContent=a.format.includes('Hybrid')?'Conflict: hybrid vs remote':'Remote compatible';$('.inspector .note p').textContent=a.id==='APP-01'?'Unknown ≠ missing. Confirm depth before claiming Playwright expertise.':a.reason;};
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderRows();announce(`Pipeline filtered: ${b.textContent}.`);}));
$('#nav-blockers').addEventListener('click',()=>{$('[data-filter="decision"]').click();$('#pipeline').scrollIntoView();});
function interview(){openDialog('Orbital Works · interview brief','<span class="badge">8 Oct 2026 · 11:00 UTC+3</span><p>Technical round · fictional interviewer Mira.</p><ul><li>Prepare a Python/pytest API regression example (F-12).</li><li>Explain PostgreSQL fixture isolation and transaction tests (F-18).</li><li>Ask how QA owns release decisions. Leadership is not yet confirmed.</li></ul><p class="muted compact">This brief prepares the conversation. It does not contact the interviewer.</p>');}
$('#interview-priority').addEventListener('click',interview);
$('#selected-memory').addEventListener('click',()=>showMemory(FIXTURES.applications.find(a=>a.id===selected).company));
$('#inspector-action').addEventListener('click',()=>{if(selected==='APP-03')showMemory('Cedar Systems');else if(['APP-02','APP-07'].includes(selected))interview();else if(selected==='APP-01')openDialog('Review resume change','<p>Bring the API testing evidence to the top of the resume. No new experience is added.</p><p class="source">Before: Tested backend services.<br>After: Built API regression tests with Python and pytest; tested PostgreSQL transaction boundaries.</p><p>Evidence: F-12, F-18. Risk: performance testing depth is unverified.</p><p><a href="../concept-b/index.html">Try the full review interaction in Concept B</a></p>');else openDialog('Next action','<p>'+FIXTURES.applications.find(a=>a.id===selected).next+'</p><p class="muted">This bounded preview shows the action context. Production execution is outside this prototype.</p>');});
renderRows();

$('[data-evidence]').replaceWith(Object.assign(document.createElement('button'),{className:'linkbutton',id:'selected-evidence',textContent:'Open evidence trail'}));$('#selected-evidence').addEventListener('click',()=>selected==='APP-06'?openDialog('Evidence unavailable','<p>This vacancy is not analyzed. No supporting Career Facts have been selected.</p>'):showEvidence());
